apiVersion: v1
kind: Secret
metadata:
  name: calyte-secrets
  namespace: default
type: Opaque
stringData:
  mongodb-uri: "mongodb+srv://username:password@cluster.mongodb.net/calyte?retryWrites=true&w=majority"
  # Add other sensitive credentials here
